_target_: src.logger.WandBWriter
project_name: "human_diffusion_combined_inference"
entity: null
run_name: "test"
mode: "online"
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
