test:
  _target_: torch.utils.data.DataLoader
  batch_size: 30
  num_workers: 15
  pin_memory: True
validation:
  _target_: torch.utils.data.DataLoader
  batch_size: 30
  num_workers: 15
  pin_memory: True
