train:
  _target_: src.datasets.DatasetWrapper
  dataset_name: "ymhao/HPDv2"
  cache_dir: null
  text_column: 'prompt'
  image_column: 'image'
  images_per_row: 2
test:
  _target_: src.datasets.DatasetWrapper
  dataset_name: "ymhao/HPDv2"
  cache_dir: null
  text_column: 'prompt'
